name: Disguise
version: 0.1
main: Disguise\BugraCNC
api: 3.11.6
author: BugraCNC

commands:
    disguise:
        description: Disguise System. (BETA)
        default: OP
    undisguise:
        description: Disguise System. (BETA)
        default: OP